name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Trigger when pushing to main branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up environment variables
        run: |
          echo "GOOGLE_SHEETS_ID=${{ secrets.GOOGLE_SHEETS_ID }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> .env
          echo "SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/healthie_backend:0.0.3
          build-args: |
            GOOGLE_SHEETS_ID=${{ secrets.GOOGLE_SHEETS_ID }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}
            SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }}
            SMTP_PORT=${{ secrets.SMTP_PORT }}
            SMTP_SERVER=${{ secrets.SMTP_SERVER }}
            

      - name: Log out from Docker Hub
        run: docker logout
